### ISSUE TITLE
multiple error when Trezor Connect dialog is forcefully closed after pressing the Export button

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#157]
error is displayed two times and/or user need to press Connect button two times (when Trezor Connect dialog is forcefully closed after pressing the `Export` button)

**Comment by sarveshwar-singh** [comment]
Also when trezor SendTx
Steps are:
1. Fill in the address and the amount fields and click next
2. Click "Send using Trezor" button
3. Close "Trezor Connect" tab before confirming the transaction on Trezor
4. *Press any button on the Trezor display"
5. Click "Send using Trezor" again

**Comment by sarveshwar-singh** [comment]
Similar:
Steps to reproduce:
1. Install Yoroi and click "Connect to Trezor Hardware Wallet"
2. Click "Next" and "Connect"
3. Go to Yoroi tab and close the "Connect to Trezor Hardware Wallet" overlay (connect.trezor page must remain open)
4. Click "Export" on the connect.trezor page
5. Reproduce all steps of the Trezor connection

Actual result: The Trezor connection process will fail each time until the user reopens the Trezor connection window (or reloads the page).

```
﻿[INFO] Yoroi v.1.0.4
[INFO] Commit: 85800752c1e7acdafcdb6999efe90e8dcb247779
[INFO] Network: mainnet
[2018-12-13T12:38:35+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.r._validateTrezor (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:60276)\n    at t.<anonymous> (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:58443)\n    at o (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440047)\n    at u._invoke (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:441451)\n    at u.e.(anonymous function) [as next] (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440226)\n    at r (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8062)\n    at chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8152",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-13T12:38:43+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.r._validateTrezor (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:60276)\n    at t.<anonymous> (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:58443)\n    at o (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440047)\n    at u._invoke (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:441451)\n    at u.e.(anonymous function) [as next] (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440226)\n    at r (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8062)\n    at chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8152",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-13T12:38:50+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.r._validateTrezor (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:60276)\n    at t.<anonymous> (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:58443)\n    at o (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440047)\n    at u._invoke (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:441451)\n    at u.e.(anonymous function) [as next] (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440226)\n    at r (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8062)\n    at chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8152",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-13T12:38:57+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.r._validateTrezor (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:60276)\n    at t.<anonymous> (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:58443)\n    at o (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440047)\n    at u._invoke (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:441451)\n    at u.e.(anonymous function) [as next] (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440226)\n    at r (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8062)\n    at chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8152",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-13T13:17:04+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.r._validateTrezor (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:60276)\n    at t.<anonymous> (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:58443)\n    at o (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440047)\n    at u._invoke (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:441451)\n    at u.e.(anonymous function) [as next] (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440226)\n    at r (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8062)\n    at chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8152",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-13T13:17:14+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.r._validateTrezor (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:60276)\n    at t.<anonymous> (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:58443)\n    at o (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440047)\n    at u._invoke (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:441451)\n    at u.e.(anonymous function) [as next] (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440226)\n    at r (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8062)\n    at chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8152",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-13T13:17:27+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.r._validateTrezor (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:60276)\n    at t.<anonymous> (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:58443)\n    at o (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440047)\n    at u._invoke (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:441451)\n    at u.e.(anonymous function) [as next] (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440226)\n    at r (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8062)\n    at chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8152",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-13T13:20:32+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.r._validateTrezor (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:60276)\n    at t.<anonymous> (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:58443)\n    at o (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440047)\n    at u._invoke (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:441451)\n    at u.e.(anonymous function) [as next] (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440226)\n    at r (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8062)\n    at chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8152",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-13T13:20:41+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.r._validateTrezor (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:60276)\n    at t.<anonymous> (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:58443)\n    at o (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440047)\n    at u._invoke (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:441451)\n    at u.e.(anonymous function) [as next] (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440226)\n    at r (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8062)\n    at chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8152",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-13T13:21:05+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.r._validateTrezor (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:60276)\n    at t.<anonymous> (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:58443)\n    at o (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440047)\n    at u._invoke (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:441451)\n    at u.e.(anonymous function) [as next] (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440226)\n    at r (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8062)\n    at chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8152",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-13T13:22:05+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.r._validateTrezor (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:60276)\n    at t.<anonymous> (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:58443)\n    at o (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440047)\n    at u._invoke (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:441451)\n    at u.e.(anonymous function) [as next] (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:440226)\n    at r (chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8062)\n    at chrome-extension://mckdcjjaabcdhpbbmnpjdpanpemmjdjk/js/yoroi.bundle.js:1:8152",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
```

**Comment by jarstorm** [comment]
Hello, and thank you for your contribution.
We're currently reviewing long-standing issues to keep the tracker manageable. As this issue hasn't seen activity in some time, we're closing it.
If the problem persists or you'd like to follow up, feel free to comment and we'll reopen it.
