### ISSUE TITLE
wrong previous session error

### ISSUE THREAD

**Issue by shinsuny** [Emurgo/yoroi-frontend#196]
`wrong previous session` error occurs when Trezor is disconnected trough "safety removal" but is still physically connected to USB port on Windows OS.

```
Pre-req: Tresor device is connected.
Steps to reproduce:
---
1. Disconnect Trezor device (I'm using safely removal USB feature)
2. Try to send ADA FROM a Trezor wallet while Trezor device is disconnected
3. Connect Trezor device when when the corresponding message appears
Expected Result: "Follow instructions on your device" message is appeared
Actual Result: "Something unexpected happened. Please retry." Error message is appeared.
---
This error is not reproduced every time.
```

```
﻿[INFO] Yoroi v.1.0.4
[INFO] Commit: 3f06f34696c83bf4ff4850ecce2053fb75437d4c
[INFO] Network: mainnet
[2018-12-27T12:37:35+03:00] TrezorConnectStore::_validateTrezor::error: wrong previous session
[2018-12-27T12:37:35+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.l._validateTrezor (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:63311)\n    at t.<anonymous> (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:61637)\n    at r (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:450261)\n    at d._invoke (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:451705)\n    at d.e.(anonymous function) [as next] (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:450440)\n    at o (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:12187)\n    at chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:12277",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-27T12:37:40+03:00] TrezorConnectStore::_validateTrezor::error: wrong previous session
[2018-12-27T12:37:40+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
  "message": "wallet.trezor.error.999: {}",
  "name": "t",
  "stack": "t: wallet.trezor.error.999: {}\n    at t.l._validateTrezor (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:63311)\n    at t.<anonymous> (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:61637)\n    at r (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:450261)\n    at d._invoke (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:451705)\n    at d.e.(anonymous function) [as next] (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:450440)\n    at o (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:12187)\n    at chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:12277",
  "id": "wallet.trezor.error.999",
  "defaultMessage": "!!!Something unexpected happened, please retry.",
  "values": {}
}
[2018-12-27T12:38:24+03:00] TrezorSendStore::_sendUsingTrezor error: {
  "stack": "Error: wrong previous session\n    at t.<anonymous> (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:435916)\n    at r (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:450261)\n    at d._invoke (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:451705)\n    at d.e.(anonymous function) [as next] (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:450440)\n    at o (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:12187)\n    at chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:12277",
  "message": "wrong previous session"
}
[2018-12-27T12:38:24+03:00] TrezorSendStore::_convertToLocalizableError::error: wrong previous session
[2018-12-27T12:38:28+03:00] TrezorSendStore::_sendUsingTrezor error: {
  "stack": "Error: wrong previous session\n    at t.<anonymous> (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:435916)\n    at r (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:450261)\n    at d._invoke (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:451705)\n    at d.e.(anonymous function) [as next] (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:450440)\n    at o (chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:12187)\n    at chrome-extension://dpelalfdpphoiflfdbcafpkgodhhfkii/js/yoroi.bundle.js:1:12277",
  "message": "wrong previous session"
}
[2018-12-27T12:38:28+03:00] TrezorSendStore::_convertToLocalizableError::error: wrong previous session
```

**Comment by jarstorm** [comment]
Hello, and thank you for your contribution.
We're currently reviewing long-standing issues to keep the tracker manageable. As this issue hasn't seen activity in some time, we're closing it.
If the problem persists or you'd like to follow up, feel free to comment and we'll reopen it.
