### ISSUE TITLE
Yoroi stuck syncing

### ISSUE THREAD

**Issue by verioxn** [Emurgo/yoroi-frontend#2109]
Yoroi Wallet on Firefox, ERG balance wouldn't update so I tried to re-sync my wallet to the blockchain. The wallet has been stuck syncing and the logs show an error has occurred. I removed and added my wallet on Firefox, same syncing issue. I tried Yoroi on Chrome, same issue as well. Here is the log from Chrome:

[INFO] Yoroi v.4.5.2
[INFO] Commit: 1925e92970a19de7457b9499d0061c36e8515929
[INFO] Network: mainnet
[INFO] User Agent: { ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36',
  browser: { name: 'Chrome', version: '90.0.4430.212', major: '90' },
  engine: { name: 'Blink', version: '90.0.4430.212' },
  os: { name: 'Mac OS', version: '10.15.7' },
  device: { vendor: undefined, model: undefined, type: undefined },
  cpu: { architecture: undefined } }
----
[2021-05-26T17:34:59-04:00] ErgoApi::refreshTransactions error: {
  "stack": "Error: addressToKind failed to parse address type Error: ergoAddressToType unknown Ergo address type 9fPiW45mZwoTxSwTLLXaZcdekqi72emebENmScyTGsjryzrntUe 01027304abbaebe8bb3a9e963dfa9fa4964d7d001e6a1bd225eadc84048ae49b627ca46238a7
    at p (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:39450)
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/955.bundle.js:1:1358276
    at Array.map (<anonymous>)
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/955.bundle.js:1:1358243
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:12522
    at async MarkUtxo (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:12332)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:10414
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:9174
    at async R (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/424.bundle.js:1:47713)
    at async ht (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:9007)",
  "message": "addressToKind failed to parse address type Error: ergoAddressToType unknown Ergo address type 9fPiW45mZwoTxSwTLLXaZcdekqi72emebENmScyTGsjryzrntUe 01027304abbaebe8bb3a9e963dfa9fa4964d7d001e6a1bd225eadc84048ae49b627ca46238a7"
}
[2021-05-26T17:34:59-04:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.GenericApiError: undefined",
  "name": "l",
  "stack": "l: api.errors.GenericApiError: undefined
    at fe.refreshTransactions (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/955.bundle.js:1:1368641)",
  "id": "api.errors.GenericApiError",
  "defaultMessage": "!!!An error occurred, please try again later.",
  "values": {}
}
[2021-05-26T17:35:15-04:00] ErgoApi::refreshTransactions error: {
  "stack": "Error: addressToKind failed to parse address type Error: ergoAddressToType unknown Ergo address type 9fPiW45mZwoTxSwTLLXaZcdekqi72emebENmScyTGsjryzrntUe 01027304abbaebe8bb3a9e963dfa9fa4964d7d001e6a1bd225eadc84048ae49b627ca46238a7
    at p (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:39450)
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/955.bundle.js:1:1358276
    at Array.map (<anonymous>)
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/955.bundle.js:1:1358243
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:12522
    at async MarkUtxo (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:12332)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:10414
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:9174
    at async R (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/424.bundle.js:1:47713)
    at async ht (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:9007)",
  "message": "addressToKind failed to parse address type Error: ergoAddressToType unknown Ergo address type 9fPiW45mZwoTxSwTLLXaZcdekqi72emebENmScyTGsjryzrntUe 01027304abbaebe8bb3a9e963dfa9fa4964d7d001e6a1bd225eadc84048ae49b627ca46238a7"
}
[2021-05-26T17:35:15-04:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.GenericApiError: undefined",
  "name": "l",
  "stack": "l: api.errors.GenericApiError: undefined
    at fe.refreshTransactions (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/955.bundle.js:1:1368641)",
  "id": "api.errors.GenericApiError",
  "defaultMessage": "!!!An error occurred, please try again later.",
  "values": {}
}

**Comment by SneakySloth89** [comment]
I am having this same issue!

**Comment by verioxn** [comment]
The issue only appears to be with Firefox and Chrome. I restored the wallet onto Microsoft Edge and it worked just fine.

**Comment by zuzunker** [comment]
Hi! A new version 4.5.3 has been published now, update whenever possible and it should solve the issue.
