### ISSUE TITLE
indefinite loader when issuing tokens on Ergo using the dapp connector

### ISSUE THREAD

**Issue by anon-real** [Emurgo/yoroi-frontend#2397]
I am using Yoroi-nighty 4.7.200 and dapp connector 0.7.0.
When trying to issue tokens, an indefinite loader appears and I get the following error in the console:
```
Failed to load resource: the server responded with a status of 400 ()
ergo.bundle.js:1 RemoteFetcher::getAssetInfo error: {
  "name": "SyntaxError",
  "message": "Unexpected ''",
  "at": 1,
  "text": ""
}
error @ ergo.bundle.js:1
ergo.bundle.js:1 batchedFetcher::batchAssetInfo error: {
  "message": "api.errors.checkAdressesInUseApiError: undefined",
  "name": "E",
  "stack": "E: api.errors.checkAdressesInUseApiError: undefined
    at Object.errorFactory (chrome-extension://poonlenmfdfbjfeeballhiibknlknepo/js/618.bundle.js:1:88337)
    at chrome-extension://poonlenmfdfbjfeeballhiibknlknepo/js/618.bundle.js:1:89006
    at async Promise.all (index 0)
    at async chrome-extension://poonlenmfdfbjfeeballhiibknlknepo/js/618.bundle.js:1:87127
    at async fe (chrome-extension://poonlenmfdfbjfeeballhiibknlknepo/js/ergo.bundle.js:1:133723)
    at async N (chrome-extension://poonlenmfdfbjfeeballhiibknlknepo/js/618.bundle.js:1:45372)
    at async he (chrome-extension://poonlenmfdfbjfeeballhiibknlknepo/js/ergo.bundle.js:1:134338)
    at async Ee._getTxAssets (chrome-extension://poonlenmfdfbjfeeballhiibknlknepo/js/ergo.bundle.js:1:186229)
    at async chrome-extension://poonlenmfdfbjfeeballhiibknlknepo/js/ergo.bundle.js:1:192555
    at async h.trigger (chrome-extension://poonlenmfdfbjfeeballhiibknlknepo/js/544.bundle.js:1:1271576)",
  "id": "api.errors.checkAdressesInUseApiError",
  "defaultMessage": "!!!Error received from server while checking used addresses.",
  "values": {}
}
error @ ergo.bundle.js:1
618.bundle.js:1 rolling back Lovefield query for
Token
EncryptionMeta with error {"id":"api.errors.checkAdressesInUseApiError","defaultMessage":"!!!Error received from server while checking used addresses.","values":{}}
N @ 618.bundle.js:1
```
<img width="1440" alt="ind" src="https://user-images.githubusercontent.com/68861503/133776276-7a956557-6150-40e6-95a9-d0673e8ebd0a.png">
 
cc @rooooooooob @vsubhuman

**Comment by zuzunker** [comment]
Hi! Nightly 4.7.201 is being pushed right now. This should be resolved there. Plz check for this version in some time and recheck the issue

**Comment by anon-real** [comment]
Great, fixed!
