### ISSUE TITLE
Yoroi extension on Chrome is stuck with white screen on launch

### ISSUE THREAD

**Issue by cardanoz** [Emurgo/yoroi-frontend#2522]
・ Yoroi Chrome version is 4.7.4
・ OS: Macbook (other user has reported on different OS too, see forum link below)
・ User has lost his recovery phrase and is dependent on his spending password to create new wallet or attempt any reinstalls
・ Not a unique case (few users have reported it before, eg: [here](https://forum.cardano.org/t/yoroi-blank-page-after-alonzo-upgrade/78978))
・ The behaviour has been present for months
・ Console Error:
```
618.bundle.js:1 rolling back Lovefield query for
KeyDerivation
Address
AddressMapping
EncryptionMeta
UtxoTransactionInput
UtxoTransactionOutput
TokenList
Token
CertificateAddress
Certificate
Transaction
Block
AccountingTransactionInput
AccountingTransactionOutput
RootDerivation
PurposeDerivation
CoinTypeDerivation
Bip44Account
Bip44Chain
CanonicalAddress with error {}
N @ 618.bundle.js:1
yoroi_bde52cb3.bundle.js:1 AdaApi::refreshTransactions error: {
  "stack": "Error: [BigNumber Error] Not a number: undefined
    at i (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/46.bundle.js:2:53381)
    at new W (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/46.bundle.js:2:44480)
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1281533
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1281597
    at Array.map (<anonymous>)
    at he (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1280437)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1282152
    at async N (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:45470)
    at async me (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1282058)
    at async Te.refreshTransactions (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:2308)",
  "message": "[BigNumber Error] Not a number: undefined"
}
error @ yoroi_bde52cb3.bundle.js:1
yoroi_bde52cb3.bundle.js:1 WalletStore::refreshWalletFromLocalOnLaunch {
  "message": "api.errors.GenericApiError: undefined",
  "name": "l",
  "stack": "l: api.errors.GenericApiError: undefined
    at Te.refreshTransactions (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:3111)
    at async i._method (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_ef4bde61.bundle.js:1:145790)",
  "id": "api.errors.GenericApiError",
  "defaultMessage": "!!!An error occurred, please try again later.",
  "values": {}
}
error @ yoroi_bde52cb3.bundle.js:1
yoroi_ef4bde61.bundle.js:1 Uncaught (in promise) l
```

**Comment by zuzunker** [comment]
Thank you for the console output details, @cardanoz!

Found a **potential** cause for this. There will be a hotfix release `4.7.500` that **might** solve the issue. Will ping here when it's pushed to the stores

**Comment by zuzunker** [comment]
@cardanoz , the version `4.7.500` is now in the stores, might take some time for auto-updates to kick in. Test it please again if possible after making sure the new version is being used. Will really appreciate any feedback on whether the issue changed in any way.

**Comment by cardanoz** [comment]
Thank you very much! !! I will tell him. 🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by cardanoz** [comment]
He has confirmed it now and seems to have fixed it! !! thank you very much! !!🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by rdlrt** [comment]
Excellent turnaround time @vsubhuman 🥇 Thanks 🙏🏻

**Comment by zuzunker** [comment]
Thank you for providing good console output report, that helped to identify the issue quickly! 🙌
