### ISSUE TITLE
fix invalid device event

### ISSUE THREAD

**Issue by shinsuny** [Emurgo/yoroi-frontend#256]
Error Log:
```
[2019-01-24T11:23:31+03:00] TrezorConnectStore::_validateTrezor::error: invalid device event
[2019-01-24T11:23:31+03:00] TrezorConnectStore::_checkAndStoreTrezorDeviceInfo {
 "message": "app.errors.unexpectedError: {}",
 "name": "UnexpectedError",
 "stack": "UnexpectedError: app.errors.unexpectedError: {}\n    at TrezorConnectStore.t._validateTrezor (chrome-extension://hbkjcgkacpgbmpaicdbooafagokchlko/js/yoroi.bundle.js:1:121382)\n    at TrezorConnectStore.<anonymous> (chrome-extension://hbkjcgkacpgbmpaicdbooafagokchlko/js/yoroi.bundle.js:1:118994)\n    at a (chrome-extension://hbkjcgkacpgbmpaicdbooafagokchlko/js/yoroi.bundle.js:1:794671)\n    at Generator._invoke (chrome-extension://hbkjcgkacpgbmpaicdbooafagokchlko/js/yoroi.bundle.js:1:795751)\n    at Generator.e.(anonymous function) [as next] (chrome-extension://hbkjcgkacpgbmpaicdbooafagokchlko/js/yoroi.bundle.js:1:794850)\n    at a (chrome-extension://hbkjcgkacpgbmpaicdbooafagokchlko/js/yoroi.bundle.js:1:9657)\n    at i (chrome-extension://hbkjcgkacpgbmpaicdbooafagokchlko/js/yoroi.bundle.js:1:9828)",
 "id": "app.errors.unexpectedError",
 "defaultMessage": "!!!Something unexpected happened. Please retry.",
 "values": {}
}
```

**Comment by jarstorm** [comment]
Hello, and thank you for your contribution.
We're currently reviewing long-standing issues to keep the tracker manageable. As this issue hasn't seen activity in some time, we're closing it.
If the problem persists or you'd like to follow up, feel free to comment and we'll reopen it.
