### ISSUE TITLE
api.errors.getBestBlockApiError

### ISSUE THREAD

**Issue by trjate** [Emurgo/yoroi-frontend#2666]
Hi, I've been unable to use Yoroi due to timeout errors today.  It may be a network issue actually, and nothing to do with the application, but just wanted to raise the issue in case.

Here is a curated form of the stack trace.  You'll have to forgive me as I'm a newb at JS and don't know the best way to share the error snippets, or what might be most relevant.

```
yoroi_bde52cb3.bundle.js:1 RemoteFetcher::checkAddressesInUse error: {
  "stack": "Error: timeout of 40000ms exceeded
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/954.bundle.js:2:43275)
    at XMLHttpRequest.d.ontimeout (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/954.bundle.js:2:39768)",
  "message": "timeout of 40000ms exceeded",
  "config": {},
  "code": "ECONNABORTED"
}
```

then

```
batchedFetcher::batchCheckAddressesInUse error: {
  "message": "api.errors.checkAdressesInUseApiError: undefined",
  "name": "W",
  "stack": "W: api.errors.checkAdressesInUseApiError: undefined
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/319.bundle.js:1:1778737
    at async Promise.all (index 0)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/319.bundle.js:1:1784950
    at async v (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/668.bundle.js:1:113027)
    at async I (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/668.bundle.js:1:112477)
    at async D (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/668.bundle.js:1:93992)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/668.bundle.js:1:94728
    at async E (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/668.bundle.js:1:94490)
    at async Object.rawScanAccount (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:83235)
    at async Object.rawScanAddresses (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:85584)",
  "id": "api.errors.checkAdressesInUseApiError",
  "defaultMessage": "!!!Error received from server while checking used addresses.",
  "values": {}
```

then
```
rolling back Lovefield query for
PublicDeriver
LastSyncInfo
KeyDerivation
Key
Address
AddressMapping
EncryptionMeta
Transaction
UtxoTransactionOutput
Bip44Chain
CanonicalAddress
UtxoTransactionInput
Block
TokenList
Certificate
CertificateAddress
AccountingTransactionInput
AccountingTransactionOutput
Token
RootDerivation
PurposeDerivation
CoinTypeDerivation
Bip44Account with error {"id":"api.errors.checkAdressesInUseApiError","defaultMessage":"!!!Error received from server while checking used addresses.","values":{}}
```
then
```
AdaApi::refreshTransactions error: {
  "message": "api.errors.checkAdressesInUseApiError: undefined",
  "name": "W",
  "stack": "W: api.errors.checkAdressesInUseApiError: undefined
....
....
```
then
```
WalletStore::refreshWalletFromRemote {
....
....
```
then
```
Uncaught (in promise) W {id: 'api.errors.checkAdressesInUseApiError', defaultMessage: '!!!Error received from server while checking used addresses.', values: {…}, message: 'api.errors.checkAdressesInUseApiError: undefined', name: 'W', …}
```
then
```
RemoteFetcher::getAccountState error: {
  "stack": "Error: timeout of 40000ms exceeded
```
then a few more, and finishing with I think the key error:
```
RemoteFetcher::getBestBlock error: {
  "stack": "Error: timeout of 40000ms exceeded
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/954.bundle.js:2:43275)
    at XMLHttpRequest.d.ontimeout (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/954.bundle.js:2:39768)",
  "message": "timeout of 40000ms exceeded",
  "config": {},
  "code": "ECONNABORTED"
}
```

**Comment by zuzunker** [comment]
Hi, @trjate ! Thank you for the report! We are experiencing some backend slowdowns, it is being investigated and hopefully can be resolved soon.

**Comment by zuzunker** [comment]
@trjate , an update to all our backends is being done at the moment and should be finished in an hour or so. This should hopefully resolve the issue

**Comment by jarstorm** [comment]
Hello, and thank you for your contribution.
We're currently reviewing long-standing issues to keep the tracker manageable. As this issue hasn't seen activity in some time, we're closing it.
If the problem persists or you'd like to follow up, feel free to comment and we'll reopen it.
