### ISSUE TITLE
Yoroi is not syncing, Cardano wallet

### ISSUE THREAD

**Issue by Jacksta66** [Emurgo/yoroi-frontend#2825]
Wallet will not sync. I removed the wallet and restored it. walled I am using is Chrome extension, I tried removing and adding the extension as well, my other two wallets imported fine, but this one did not (this one has quite a few more transactions though). Works fine on Iphone.

```
[INFO] Yoroi v.4.11.500
[INFO] Commit: d6f61956961bf4a04636a833fced870aa7609006
[INFO] Network: mainnet
[INFO] User Agent: { ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36',
  browser: { name: 'Chrome', version: '100.0.4896.127', major: '100' },
  engine: { name: 'Blink', version: '100.0.4896.127' },
  os: { name: 'Windows', version: '10' },
  device: { vendor: undefined, model: undefined, type: undefined },
  cpu: { architecture: 'amd64' } }
----
[2022-04-18T01:50:31+10:00] RemoteFetcher::getTransactionsHistoryForAddresses error: {
  "stack": "Error: Request failed with status code 504
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:43209)
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:45611)
    at XMLHttpRequest.d.onreadystatechange (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:39429)",
  "message": "Request failed with status code 504",
  "config": {}
}
[2022-04-18T01:50:31+10:00] batchedFetcher::batchGetTransactionsHistoryForAddresses error: {
  "message": "api.errors.getTxHistoryForAddressesApiError: undefined",
  "name": "_",
  "stack": "_: api.errors.getTxHistoryForAddressesApiError: undefined
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:12357
    at async N (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:8426)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5712
    at async Promise.all (index 1)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5749
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5635
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1298457
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297230
    at async S (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:74125)
    at async ke (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297063)",
  "id": "api.errors.getTxHistoryForAddressesApiError",
  "defaultMessage": "!!!Error received from server while getting txs.",
  "values": {}
}
[2022-04-18T01:50:31+10:00] AdaApi::refreshTransactions error: {
  "message": "api.errors.getTxHistoryForAddressesApiError: undefined",
  "name": "_",
  "stack": "_: api.errors.getTxHistoryForAddressesApiError: undefined
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:12357
    at async N (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:8426)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5712
    at async Promise.all (index 1)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5749
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5635
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1298457
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297230
    at async S (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:74125)
    at async ke (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297063)",
  "id": "api.errors.getTxHistoryForAddressesApiError",
  "defaultMessage": "!!!Error received from server while getting txs.",
  "values": {}
}
[2022-04-18T01:50:31+10:00] RemoteFetcher::getTransactionsHistoryForAddresses error: {
  "stack": "Error: Request failed with status code 504
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:43209)
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:45611)
    at XMLHttpRequest.d.onreadystatechange (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:39429)",
  "message": "Request failed with status code 504",
  "config": {}
}
[2022-04-18T01:50:32+10:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.getTxHistoryForAddressesApiError: undefined",
  "name": "_",
  "stack": "_: api.errors.getTxHistoryForAddressesApiError: undefined
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:12357
    at async N (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:8426)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5712
    at async Promise.all (index 1)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5749
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5635
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1298457
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297230
    at async S (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:74125)
    at async ke (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297063)",
  "id": "api.errors.getTxHistoryForAddressesApiError",
  "defaultMessage": "!!!Error received from server while getting txs.",
  "values": {}
}
[2022-04-18T01:51:21+10:00] RemoteFetcher::getAccountState error: {
  "stack": "Error: Request failed with status code 504
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:43209)
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:45611)
    at XMLHttpRequest.d.onreadystatechange (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:39429)",
  "message": "Request failed with status code 504",
  "config": {}
}
[2022-04-18T01:51:21+10:00] batchedFetcher::batchGetAccountState error: {
  "message": "api.errors.getAccountStateApiError: undefined",
  "name": "N",
  "stack": "N: api.errors.getAccountStateApiError: undefined
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:14628
    at async Promise.all (index 0)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:6832
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_7d7d3f08.bundle.js:1:206778
    at async Promise.all (index 0)
    at async Mn.refreshDelegation (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_7d7d3f08.bundle.js:1:207676)
    at async e (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_7d7d3f08.bundle.js:1:210727)",
  "id": "api.errors.getAccountStateApiError",
  "defaultMessage": "!!!Error received from server while getting account state.",
  "values": {}
}
[2022-04-18T01:51:23+10:00] RemoteFetcher::getTransactionsHistoryForAddresses error: {
  "stack": "Error: Request failed with status code 504
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:43209)
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:45611)
    at XMLHttpRequest.d.onreadystatechange (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:39429)",
  "message": "Request failed with status code 504",
  "config": {}
}
[2022-04-18T01:51:23+10:00] batchedFetcher::batchGetTransactionsHistoryForAddresses error: {
  "message": "api.errors.getTxHistoryForAddressesApiError: undefined",
  "name": "_",
  "stack": "_: api.errors.getTxHistoryForAddressesApiError: undefined
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:12357
    at async N (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:8426)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5712
    at async Promise.all (index 0)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5749
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5635
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1298457
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297230
    at async S (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:74125)
    at async ke (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297063)",
  "id": "api.errors.getTxHistoryForAddressesApiError",
  "defaultMessage": "!!!Error received from server while getting txs.",
  "values": {}
}
[2022-04-18T01:51:23+10:00] AdaApi::refreshTransactions error: {
  "message": "api.errors.getTxHistoryForAddressesApiError: undefined",
  "name": "_",
  "stack": "_: api.errors.getTxHistoryForAddressesApiError: undefined
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:12357
    at async N (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:8426)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5712
    at async Promise.all (index 0)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5749
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5635
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1298457
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297230
    at async S (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:74125)
    at async ke (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297063)",
  "id": "api.errors.getTxHistoryForAddressesApiError",
  "defaultMessage": "!!!Error received from server while getting txs.",
  "values": {}
}
[2022-04-18T01:51:23+10:00] RemoteFetcher::getTransactionsHistoryForAddresses error: {
  "stack": "Error: Request failed with status code 504
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:43209)
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:45611)
    at XMLHttpRequest.d.onreadystatechange (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:39429)",
  "message": "Request failed with status code 504",
  "config": {}
}
[2022-04-18T01:51:23+10:00] RemoteFetcher::getTransactionsHistoryForAddresses error: {
  "stack": "Error: Request failed with status code 504
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:43209)
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:45611)
    at XMLHttpRequest.d.onreadystatechange (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:39429)",
  "message": "Request failed with status code 504",
  "config": {}
}
[2022-04-18T01:51:23+10:00] RemoteFetcher::getTransactionsHistoryForAddresses error: {
  "stack": "Error: Request failed with status code 504
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:43209)
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:45611)
    at XMLHttpRequest.d.onreadystatechange (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/0.bundle.js:2:39429)",
  "message": "Request failed with status code 504",
  "config": {}
}
[2022-04-18T01:51:24+10:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.getTxHistoryForAddressesApiError: undefined",
  "name": "_",
  "stack": "_: api.errors.getTxHistoryForAddressesApiError: undefined
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:12357
    at async N (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:8426)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5712
    at async Promise.all (index 0)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5749
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:5635
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1298457
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297230
    at async S (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/205.bundle.js:1:74125)
    at async ke (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/289.bundle.js:1:1297063)",
  "id": "api.errors.getTxHistoryForAddressesApiError",
  "defaultMessage": "!!!Error received from server while getting txs.",
  "values": {}
}
```

**Comment by ThannDev** [comment]
Do you still having the same issues?

**Comment by Jacksta66** [comment]
Hey mate, seems to be syncing now. Cheers. This one can be closed.
