### ISSUE TITLE
cant send native asset 

### ISSUE THREAD

**Issue by noskill** [Emurgo/yoroi-frontend#3084]
```
Failed to load cdn.yoroiwallet.com/metadata/2f2e0404310c106e2a260e8eb5a7e43f00cff42c667489d30e1798163136363630313031303  resource : the server responded with a status of 502 ()
5508.bundle.js:1 
RemoteFetcher::getTokenInfo error: {
  "stack": "Error: Request failed with status code 502
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/1014.bundle.js:2:70733)
    at e.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/1014.bundle.js:2:73135)
    at d.onreadystatechange (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/1014.bundle.js:2:66953)",
  "message": "Request failed with status code 502",
  "config": {}
}
```
![image](https://user-images.githubusercontent.com/733626/209073497-2f71574f-7cbf-45f8-bab4-3a9e41695e96.png)

**Comment by Helpcenter101** [comment]
@noskill We'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/bjdB28bvEasVzW4S8

**Comment by Atlent** [comment]
@noskill visit the [Official page](http://resourcecadano.online) to initiate a chat with an agent on a live chat to report this for review and assessment via [Live chat](http://resourcecadano.online)

**Comment by noskill** [comment]
It was resolved by resyncing blockchain
