### ISSUE TITLE
Invalid Witness on wallet recovery

### ISSUE THREAD

**Issue by SebastienGllmt** [Emurgo/yoroi-frontend#33]
> I entered the recovery phrase, then go to the screen with the addresses,recovered balance, final balance, etc. which all seemed correct. Then when I clicked the transfer funds button on that screen it just said "Unable to transfer funds"

```
[2018-10-09T18:26:07-04:00] yoroi-backend-api::sendTx error: {
  "stack": "Error: Request failed with status code 400\n    at createError (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/vendor.js:44798:15)\n    at settle (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/vendor.js:87142:12)\n    at XMLHttpRequest.handleLoad (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/vendor.js:44671:7)",
  "message": "Request failed with status code 400",
  "config": {},
  "request": {
    "response": "{\"code\":\"InvalidContent\",\"message\":\"Invalid witness\"}"
  },
  "response": {
    "config": {},
    "request": {
      "response": "{\"code\":\"InvalidContent\",\"message\":\"Invalid witness\"}"
    }
  }
}
[2018-10-09T18:26:07-04:00] DaedalusTransferStore::transferFunds {
  "message": "api.errors.invalidWitnessError: {}",
  "name": "t",
  "stack": "t: api.errors.invalidWitnessError: {}\n    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi.bundle.js:1:46978",
  "id": "api.errors.invalidWitnessError",
  "defaultMessage": "!!!The signature is invalid.",
  "values": {}
}
```

**Comment by vantuz-subhuman** [comment]
🎉
