### ISSUE TITLE
Chrome errors don't show up in logs

### ISSUE THREAD

**Issue by SebastienGllmt** [Emurgo/yoroi-frontend#41]
**Note**: The example errors in this issue all originate from accidentally having 2 copies of Yoroi running in the same browser so don't bother investigating them.

Errors such as 

`OPTIONS https://iohk-mainnet.yoroiwallet.com/api/txs/history 502`

`OPTIONS https://iohk-mainnet.yoroiwallet.com/api/txs/history net::ERR_NETWORK_CHANGED`

are generic network errors that occur in the console but don't show up when you try and download logs as they were not explicitly generated by Yoroi. However, these errors cause real errors later on.

This can actually get really bad in cases such as uncaught exceptions which appear in the Chrome log but don't actually show up in the Yoroi logs

**Example**: The follow doesn't show up if you download Yoroi logs
```
yoroi.bundle.js:1 Uncaught (in promise) 
t {id: "api.errors.GenericApiError", defaultMessage: "!!!An error occurred, please try again later.", values: {…}, message: "api.errors.GenericApiError: {}", name: "t", …}
defaultMessage: "!!!An error occurred, please try again later."
id: "api.errors.GenericApiError"
values: {}
message: "api.errors.GenericApiError: {}"
name: "t"
stack: "t: api.errors.GenericApiError: {}↵    at t.<anonymous> (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi.bundle.js:1:132197)↵    at a (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi.bundle.js:1:421708)↵    at c._invoke (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi.bundle.js:1:423112)↵    at c.e.(anonymous function) [as throw] (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi.bundle.js:1:421887)↵    at r (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi.bundle.js:1:6312)↵    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi.bundle.js:1:6427
```

**Suggested fix**: 
1) Don't allow two copies of Yoroi at the same time (not easy apparently)
1) See if we can somehow add a hook to watch generic Chrome errors and add those to our logs also

**Comment by jarstorm** [comment]
Hello, and thank you for your contribution.
We're currently reviewing long-standing issues to keep the tracker manageable. As this issue hasn't seen activity in some time, we're closing it.
If the problem persists or you'd like to follow up, feel free to comment and we'll reopen it.
